---
title: 'Statistical design: Hydrochemical assessment of Semarang groundwater system'
author: 
  - name: Dasapta Erwin Irawan
    affiliation: Faculty of Earth Sciences and Technology, Institut Teknologi Bandung
  - name: Thomas Adi Putranto
    affiliation: Dept of Geology, Faculty of Engineering, Universitas Diponegoro
date: "July 4, 2016"
output:
  pdf_document:
    toc: true
    highlight: zenburn
    number_sections: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
abstract: 
    The following paper describes in statistical treatment and analysis based on the data set related to our project "Hydrochemical assessment of Semarang Groundwater Quality". All of 58 samples were taken in 2014 using well point data from several reports from Ministry of Energy and Mineral Resources and independent consultant. The data set is formatted as plain csv for easy loading.
    This paper contains data preparation and data treatment including correlation matrix, cluster analysis using kmeans and hierarchical cluster analysis, and principal component analysis. We used R statistical program with the support of the following statistical packages, `aaa`, `bbb`, `ccc`, `ggplot2`, `dplyr`, `factomineR`, `factoExtra`, `cluster`,  `ddd`, and `eee`.  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

```Note: The ESSD EGU journal is chosen for submission on LaTeX, we move the site and the text to Overleaf platform```

The interactions between groundwater and surface water is still one of the favorite subject in the field o hydrogeology, especially if it relates to the water quality in urban area and coastal area. Semarang is one of the vastly developed big city in north coast of Java. Located in the mid Java Province, it lies in the middle of north route road that connects the West Java and East Java Province. The following paper describes in brief the data set related to our project "Hydrochemical assessment of Semarang Groundwater Quality". 

<< more description >>

Figure 1 The location of study area.


# General description of the dataset

+ Improvement of a functional annotation of Hordeum vulgare genome draft.
+ This dataset provides the list of all up- and down-regulated genes during one day long desiccation and subsequent re-watering separately in roots and upper part of 4-week-old barley seedlings.
+ Enriched gene ontology (GO) term analysis highlights processes targeted by above mentioned conditions.
+ The dataset can serve as a source of candidate genes for markers used for drought associated studies.

# Geographical coverage

The sampling area is Semarang area, the capital of Mid Java Province, Java, Indonesia. The coordinate of the area is AAA, BBB.

# Statistical design

## Data preparation 

All of 58 samples were taken in 2014 using well point data from several reports from Ministry of Energy and Mineral Resources and independent consultant. We provided 20 parameters in each samples (sample id,  coord X, coord Y, well depth, water level, water elevation, TDS, pH, EC, K, Ca, Na, Mg, Cl, SO4, HCO3, year, ion balance, screen location, and chemical facies). The chemical composition were tested in the Water Quality Laboratory, Universitas Diponegoro using mass spectrofotometer method.

# Data analysis

## Correlation matrix

aaa

## Hierarchical cluster analysis (CA)

bbb

## Principal component analysis (PCA)

ccc


# References

+ STHDA
+ CRAN
+ Little red book on multivariate analysis
+ Irawan, DE. and Putranto, TA., 2016, Multivariate analysis using R: a worlflow based on hydrochemical data from Semarang area, RioJournal single media publication.
+ Irawan, DE. and Putranto, TA., 2016, Data set: Hydrochemical assessment of Semarang groundwater system, Zenodo repository.
+ add paper Ijog
+ add some references in geology
+ add some references in hydrogeology
